name: lint

on:
  pull_request:
  # Also build the default branch so cache is available to PRs.
  push:
    branches: [main]

jobs:
  selene:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config selene.toml --color always ./lua
